Traceback (most recent call last):
  File "C:\Users\rullu\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\rullu\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\rullu\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "C:\Users\rullu\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\rullu\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "C:\Users\rullu\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\rullu\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# def factorial_for(num):


# def factorial_recursive(num):

import time
start_time = time.time()
factorial_for(600)
time_for = time.time() - start_time

start_time = time.time()
factorial_recursive(600)
time_recursive = time.time() - start_time

print("Time for iterative approach:", round(time_for, 4), "minutes")
print("Time for recursive approach:", round(time_recursive, 4), "minutes")
------------------


[1;31m-----------------------------------------------------------[0m
[1;31mNameError[0m                 Traceback (most recent call last)
Cell [1;32mIn[3], line 8[0m
[0;32m      6[0m [38;5;28;01mimport[39;00m[38;5;250m [39m[38;5;21;01mtime[39;00m
[0;32m      7[0m start_time [38;5;241m=[39m time[38;5;241m.[39mtime()
[1;32m----> 8[0m [43mfactorial_for[49m([38;5;241m600[39m)
[0;32m      9[0m time_for [38;5;241m=[39m time[38;5;241m.[39mtime() [38;5;241m-[39m start_time
[0;32m     11[0m start_time [38;5;241m=[39m time[38;5;241m.[39mtime()

[1;31mNameError[0m: name 'factorial_for' is not defined

